/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Cake1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cake1.gltf')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
      <mesh geometry={nodes.pSphere550.geometry} material={materials['1001']} position={[-0.602, 0.794, -0.575]} rotation={[1.569, -0.004, -2.425]} scale={0.088} />
      <mesh geometry={nodes.pSphere551.geometry} material={materials['1001']} position={[-0.764, 0.795, -0.338]} rotation={[1.569, -0.004, -2.774]} scale={0.088} />
      <mesh geometry={nodes.pSphere546.geometry} material={materials['1001']} position={[0.459, 0.79, -0.679]} rotation={[1.569, -0.004, -1.029]} scale={0.088} />
      <mesh geometry={nodes.pSphere547.geometry} material={materials['1001']} position={[0.197, 0.79, -0.798]} rotation={[1.569, -0.004, -1.378]} scale={0.088} />
      <mesh geometry={nodes.pSphere545.geometry} material={materials['1001']} position={[0.665, 0.789, -0.478]} rotation={[1.569, -0.004, -0.68]} scale={0.088} />
      <mesh geometry={nodes.pSphere544.geometry} material={materials['1001']} position={[0.789, 0.789, -0.218]} rotation={[1.569, -0.004, -0.331]} scale={0.088} />
      <mesh geometry={nodes.Base.geometry} material={materials.Base} position={[-0.005, -0.417, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.981}>
        <mesh geometry={nodes.Base001.geometry} material={materials['1001']} />
      </mesh>
      <mesh geometry={nodes.Frosting.geometry} material={materials.Frosting} position={[-0.005, -0.413, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.978}>
        <mesh geometry={nodes.pCylinder3001.geometry} material={materials['1001']} />
      </mesh>
      <mesh geometry={nodes.pCylinder29.geometry} material={materials['1004']} position={[0.011, 3.375, 0.009]} rotation={[1.569, -0.004, 0.019]} scale={1.205} />
      <mesh geometry={nodes.pSphere561.geometry} material={materials['1001']} position={[0.817, 0.79, 0.069]} rotation={[1.569, -0.004, 0.019]} scale={0.088} />
      <mesh geometry={nodes.pSphere560.geometry} material={materials['1001']} position={[0.746, 0.79, 0.348]} rotation={[1.569, -0.004, 0.368]} scale={0.088} />
      <mesh geometry={nodes.pSphere558.geometry} material={materials['1001']} position={[0.349, 0.793, 0.753]} rotation={[1.569, -0.004, 1.066]} scale={0.088} />
      <mesh geometry={nodes.pSphere559.geometry} material={materials['1001']} position={[0.583, 0.792, 0.585]} rotation={[1.569, -0.004, 0.717]} scale={0.088} />
      <mesh geometry={nodes.pSphere557.geometry} material={materials['1001']} position={[0.072, 0.794, 0.83]} rotation={[1.569, -0.004, 1.415]} scale={0.088} />
      <mesh geometry={nodes.pSphere556.geometry} material={materials['1001']} position={[-0.216, 0.795, 0.808]} rotation={[1.569, -0.004, 1.764]} scale={0.088} />
      <mesh geometry={nodes.pSphere555.geometry} material={materials['1001']} position={[-0.478, 0.796, 0.689]} rotation={[1.569, -0.004, 2.113]} scale={0.088} />
      <mesh geometry={nodes.Candle.geometry} material={materials['1005']} position={[-0.005, -0.428, 0.016]} rotation={[1.569, -0.004, 0.019]}>
        <mesh geometry={nodes.Candle001.geometry} material={materials['1006']} />
        <mesh geometry={nodes.Candle002.geometry} material={materials['1007']} />
      </mesh>
      <mesh geometry={nodes.pSphere548.geometry} material={materials['1001']} position={[-0.09, 0.792, -0.82]} rotation={[1.569, -0.004, -1.727]} scale={0.088} />
      <mesh geometry={nodes.pSphere549.geometry} material={materials['1001']} position={[-0.367, 0.793, -0.743]} rotation={[1.569, -0.004, -2.076]} scale={0.088} />
      <mesh geometry={nodes.pSphere553.geometry} material={materials['1001']} position={[-0.808, 0.796, 0.228]} rotation={[1.569, -0.004, 2.811]} scale={0.088} />
      <mesh geometry={nodes.pSphere554.geometry} material={materials['1001']} position={[-0.683, 0.797, 0.487]} rotation={[1.569, -0.004, 2.462]} scale={0.088} />
      <mesh geometry={nodes.pSphere552.geometry} material={materials['1001']} position={[-0.836, 0.796, -0.059]} rotation={[1.569, -0.004, -3.123]} scale={0.088} />
      <mesh geometry={nodes.Frosting2L1.geometry} material={materials['Frosting.001']} position={[0.01, -0.68, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.978} />
      <mesh geometry={nodes.Frosting2L2.geometry} material={materials['Frosting.002']} position={[0.01, 0.391, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.779} />
      <mesh geometry={nodes.Base2L1.geometry} material={materials['Base.004']} position={[0.01, -0.683, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.981} />
      <mesh geometry={nodes.Base2L2.geometry} material={materials['Base.005']} position={[0.01, 0.388, 0.016]} rotation={[1.569, -0.004, 0.019]} scale={0.782} />
      <mesh geometry={nodes.Plate.geometry} material={materials['1004.001']} position={[0.022, 3.109, 0.009]} rotation={[1.569, -0.004, 0.019]} scale={1.205} />
      <mesh geometry={nodes.pSphere2L017.geometry} material={materials['1001.003']} position={[0.713, 1.363, 0.035]} rotation={[1.569, -0.004, 0.019]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L016.geometry} material={materials['1001.003']} position={[0.653, 1.364, 0.268]} rotation={[1.569, -0.004, 0.368]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L015.geometry} material={materials['1001.003']} position={[0.517, 1.365, 0.467]} rotation={[1.569, -0.004, 0.717]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L014.geometry} material={materials['1001.003']} position={[0.321, 1.366, 0.607]} rotation={[1.569, -0.004, 1.066]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L013.geometry} material={materials['1001.003']} position={[0.089, 1.367, 0.672]} rotation={[1.569, -0.004, 1.415]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L012.geometry} material={materials['1001.003']} position={[-0.151, 1.368, 0.653]} rotation={[1.569, -0.004, 1.764]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L011.geometry} material={materials['1001.003']} position={[-0.37, 1.368, 0.554]} rotation={[1.569, -0.004, 2.113]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L010.geometry} material={materials['1001.003']} position={[-0.542, 1.369, 0.385]} rotation={[1.569, -0.004, 2.462]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L009.geometry} material={materials['1001.003']} position={[-0.646, 1.369, 0.168]} rotation={[1.569, -0.004, 2.811]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L008.geometry} material={materials['1001.003']} position={[-0.67, 1.368, -0.072]} rotation={[1.569, -0.004, -3.123]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L007.geometry} material={materials['1001.003']} position={[-0.61, 1.368, -0.305]} rotation={[1.569, -0.004, -2.774]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L006.geometry} material={materials['1001.003']} position={[-0.474, 1.367, -0.503]} rotation={[1.569, -0.004, -2.425]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L005.geometry} material={materials['1001.003']} position={[-0.278, 1.366, -0.644]} rotation={[1.569, -0.004, -2.076]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L004.geometry} material={materials['1001.003']} position={[-0.046, 1.365, -0.708]} rotation={[1.569, -0.004, -1.727]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L003.geometry} material={materials['1001.003']} position={[0.194, 1.364, -0.69]} rotation={[1.569, -0.004, -1.378]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L002.geometry} material={materials['1001.003']} position={[0.413, 1.363, -0.59]} rotation={[1.569, -0.004, -1.029]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L001.geometry} material={materials['1001.003']} position={[0.585, 1.363, -0.422]} rotation={[1.569, -0.004, -0.68]} scale={0.073} />
      <mesh geometry={nodes.pSphere2L.geometry} material={materials['1001.003']} position={[0.689, 1.363, -0.205]} rotation={[1.569, -0.004, -0.331]} scale={0.073} />
    </group>
  )
}

useGLTF.preload('/Cake1.gltf')
